name: PR created or updated

on:
  pull_request:
    types: [opened]

jobs:
  print_body:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
    steps:
      - name: print
        run: echo "${{ github.event.pull_request.body }}"
