name: Check RAP fields

on:
  pull_request:
    types: [opened, edited]

jobs:
  check_rap_fields:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
    env:
      JIRA_URL: ${{ secrets.JIRA_URL}}
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL}}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN}}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install requirements
        run: pip install -r requirements.txt

      - name: save body to file
        run: echo "${{ github.event.pull_request.body }}" > pr_body

      - name: run script
        run: |
          python main.py
