name: PR created or updated

on:
  pull_request:
    branches:
      - main
  issue_comment:
    types:
      - created
      - edited

jobs:
  print_body:
    runs-on: ubunut-latest
    permissions:
      contents: read
      issues: read
    steps:
      - name: print
        run: echo ${{  github.event.comment }}
